export type TConfigProps = Record<
  | 'ProductionKey'
  | 'DeviceKeyIdentifier'
  | 'BaseURL'
  | 'PublicFaceScanEncryptionKey'
  | 'sessionId'
  | 'idScanId',
  string
> & {
  flow: number;
};

export type TInitializeFromAutogeneratedConfigCallback = (
  result: boolean
) => void;
